### ISSUE TITLE
Overlapping of long site title and menu in mobile version

### ISSUE THREAD

**Issue by SeniorSpielbergo** [BenSibley/tracks#56]
I am using your theme on my website (www.david-wille.de). The theme really looks great even on my small Nexus 4 screen, but I identified an unpleasant overlapping of my site title "David Wille | Photography" and the menu of the mobile layout.

Steps to reproduce:

1. Open my website: www.david-wille.de on a mobile device with a 4" screen.
2. Click on the menu button.

You can see that the line break of the page title "David Wille | Photography" causes the first entry in the menu to be overlaped by the page title.

**Comment by BenSibley** [comment]
Hey thanks for catching that. Looks like I'll need to add some JS to reposition the menu based on the site title's height. Kind of an ugly solution, but it will have to do.

For now, you can use the following to keep the menu below the site title on your site at mobile widths:

@media all and (max-width: 500px) {
  
  #menu-primary {
    padding-top: 144px !important;
  }
}

**Comment by SeniorSpielbergo** [comment]
Thanks for your quick reply. This fixed the problem.
You do a really great job and I really like the theme!

**Comment by BenSibley** [comment]
Yea no problem, thanks for the kind words :)
